### ISSUE TITLE
Issue not working

### ISSUE THREAD

**Issue by Andrejki** [cipher387/quickgeolocationsearch#1]
Hi. This is not working anymore
Best regards

**Comment by cipher387** [comment]
"Hi. This is not working anymore" - why?

 I've just checked all the buttons and they open the maps with the right coordinates. At what stage are you having problems?

**Comment by Andrejki** [comment]
Hi. Thank you for your reply sincerely.
The tool on the website is working, but the code here is not working.
See it below. But in any case, as long as the tool is working, it is ok?
Kind regards


node script.js returns this:


/home/andrejki/quickgeolocationsearch/script.js:1
ymaps = window.ymaps;
^

ReferenceError: window is not defined
    at Object.<anonymous> (/home/andrejki/quickgeolocationsearch/script.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by cipher387** [comment]
This script is by no means meant to be run using node.js. How did you come up with this in the first place?

**Comment by Andrejki** [comment]
How to start it?
Node.js and node on script.js don t work.

I ve opened html and it is working, so is this solved?

**Comment by cipher387** [comment]
"I ve opened html and it is working, so is this solved?" - yes. It just simple webpage.
